version: '3.5'

services:
#  api1:
#    image: rivelles/rinhabackend:latest
#    hostname: api1
#    depends_on:
#      - db
#      - redis
#    expose:
#      - "80"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.25'
#          memory: '0.4GB'
#
#  api2:
#    image: rivelles/rinhabackend:latest
#    hostname: api2
#    depends_on:
#      - db
#      - redis
#    expose:
#      - "80"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.25'
#          memory: '0.4GB'
#
#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - api01
#      - api02
#    ports:
#      - "9999:9999"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.2'
#          memory: '0.5GB'

  db:
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rinha
    command: postgres -c work_mem=512MB
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1.7GB'

networks:
  default:
    driver: bridge
